version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout

      - run:
          name: "branch checking"
          command: |
            files=`git diff master $CIRCLE_BRANCH --name-only | grep ".php"`
            for file in $files; do
              php $file
            done