version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      
      # check basic syntax 
      - run: bash ./.circleci/diff_test.sh
      
      # lesson checking
      #- run: bash ./.circleci/diff_test.sh
      
      # javascript checking
      #- run: bash ./.circleci/diff_test.sh