version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      
      - run:
          name: "Preparing environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      - run:
          name: "Checking PHP Syntax"
          command: |
            php index.php