version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout

      - run:
          name: "branch checking"
          command: |
            echo $CIRCLE_BRANCH
            git diff master $CIRCLE_BRANCH --name-only

      - run:
          name: "Checking PHP Syntax"
          command: |
            php index.php
