name: PHP Composer

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: "running unit test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "syntax error check"
      run: |
        bash .github/shell/diff_test.sh
